name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # B1: Lấy code từ repo
      - name: Checkout code
        uses: actions/checkout@v4

      # B2: Đăng nhập Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # B3: Build Docker images theo docker-compose.yml
      - name: Build Docker images
        run: docker compose build

      # B4: Push image lên Docker Hub
      - name: Push Docker images
        run: |
          docker tag product ${{ secrets.DOCKERHUB_USERNAME }}/product:latest
          docker tag order ${{ secrets.DOCKERHUB_USERNAME }}/order:latest
          docker tag api-gateway ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/product:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/order:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
