name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: docker compose build

      - name: Push Docker images
        run: |
          docker tag product ${{ secrets.DOCKER_USERNAME }}/product:latest
          docker tag order ${{ secrets.DOCKER_USERNAME }}/order:latest
          docker tag api-gateway ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/product:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/order:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
